# Generated by Django 5.1.6 on 2025-02-07 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockStatement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(default=0, verbose_name='銘柄コード')),
                ('year', models.IntegerField(default=2025, verbose_name='年度')),
                ('total_assets', models.IntegerField(blank=True, null=True, verbose_name='総資産')),
                ('net_assets', models.IntegerField(blank=True, null=True, verbose_name='純資産')),
                ('shareholders_equity', models.IntegerField(blank=True, null=True, verbose_name='株主資本')),
                ('retained_earnings', models.IntegerField(blank=True, null=True, verbose_name='利益剰余金')),
                ('short_term_loans', models.IntegerField(blank=True, null=True, verbose_name='短期借入金')),
                ('long_term_loans', models.IntegerField(default=0, verbose_name='長期借入金')),
                ('bps', models.IntegerField(default=0, verbose_name='BPS (1株あたり純資産)')),
                ('equity_ratio', models.IntegerField(blank=True, null=True, verbose_name='自己資本比率')),
                ('operating_cf', models.IntegerField(blank=True, null=True, verbose_name='営業キャッシュフロー')),
                ('investing_cf', models.IntegerField(default=0, verbose_name='投資キャッシュフロー')),
                ('financing_cf', models.IntegerField(default=0, verbose_name='財務キャッシュフロー')),
                ('capital_expenditure', models.IntegerField(blank=True, null=True, verbose_name='設備投資')),
                ('cash_equivalents', models.IntegerField(blank=True, null=True, verbose_name='現金同等物')),
                ('operating_cf_margin', models.IntegerField(default=0, verbose_name='営業CFマージン')),
                ('revenue', models.IntegerField(default=0, verbose_name='売上高')),
                ('operating_income', models.IntegerField(blank=True, null=True, verbose_name='営業利益')),
                ('ordinary_income', models.IntegerField(blank=True, null=True, verbose_name='経常利益')),
                ('net_income', models.IntegerField(blank=True, null=True, verbose_name='純利益')),
                ('eps', models.IntegerField(blank=True, null=True, verbose_name='EPS (1株当たり利益)')),
                ('roe', models.IntegerField(default=0, verbose_name='ROE (自己資本利益率)')),
                ('roa', models.IntegerField(blank=True, null=True, verbose_name='ROA (総資産利益率)')),
                ('dividend_per_share', models.IntegerField(blank=True, null=True, verbose_name='一株配当')),
                ('retained_earnings_dividends', models.IntegerField(blank=True, null=True, verbose_name='剰余金の配当')),
                ('share_buyback', models.IntegerField(blank=True, null=True, verbose_name='自社株買い')),
                ('dividend_payout_ratio', models.IntegerField(default=0, verbose_name='配当性向')),
                ('total_return_ratio', models.IntegerField(blank=True, null=True, verbose_name='総還元性向')),
                ('net_asset_dividend_ratio', models.IntegerField(blank=True, null=True, verbose_name='純資産配当率')),
                ('result', models.IntegerField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('proba', models.FloatField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('registered_date', models.DateField(default=datetime.date(2025, 2, 7))),
            ],
        ),
    ]
