# Generated by Django 5.1.6 on 2025-02-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twoxstockfinderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockstatement',
            name='bps',
            field=models.FloatField(default=592.01, verbose_name='BPS (1株あたり純資産)'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='code',
            field=models.IntegerField(default=7105, verbose_name='銘柄コード'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='dividend_payout_ratio',
            field=models.FloatField(default=118.9, verbose_name='配当性向'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='eps',
            field=models.FloatField(blank=True, null=True, verbose_name='EPS (1株当たり利益)'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='equity_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='自己資本比率'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='financing_cf',
            field=models.IntegerField(default=-4601000000, verbose_name='財務キャッシュフロー'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='investing_cf',
            field=models.IntegerField(default=-19243000000, verbose_name='投資キャッシュフロー'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='long_term_loans',
            field=models.IntegerField(default=131678000000, verbose_name='長期借入金'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='net_asset_dividend_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='純資産配当率'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='operating_cf_margin',
            field=models.FloatField(default=4.43, verbose_name='営業CFマージン'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='revenue',
            field=models.IntegerField(default=465406000000, verbose_name='売上高'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='roa',
            field=models.FloatField(blank=True, null=True, verbose_name='ROA (総資産利益率)'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='roe',
            field=models.FloatField(default=1.14, verbose_name='ROE (自己資本利益率)'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='total_return_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='総還元性向'),
        ),
    ]
