# Generated by Django 5.1.6 on 2025-02-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twoxstockfinderapp', '0004_alter_stockstatement_operating_cf_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockstatement',
            name='capital_expenditure',
            field=models.FloatField(blank=True, null=True, verbose_name='設備投資'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='cash_equivalents',
            field=models.FloatField(blank=True, null=True, verbose_name='現金同等物'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='dividend_per_share',
            field=models.FloatField(blank=True, null=True, verbose_name='一株配当'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='financing_cf',
            field=models.FloatField(blank=True, default=-4601000000, null=True, verbose_name='財務キャッシュフロー'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='investing_cf',
            field=models.FloatField(blank=True, default=-19243000000, null=True, verbose_name='投資キャッシュフロー'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='long_term_loans',
            field=models.FloatField(blank=True, default=131678000000, null=True, verbose_name='長期借入金'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='net_assets',
            field=models.FloatField(blank=True, null=True, verbose_name='純資産'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='net_income',
            field=models.FloatField(blank=True, null=True, verbose_name='純利益'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='operating_cf',
            field=models.FloatField(blank=True, null=True, verbose_name='営業キャッシュフロー'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='operating_income',
            field=models.FloatField(blank=True, null=True, verbose_name='営業利益'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='ordinary_income',
            field=models.FloatField(blank=True, null=True, verbose_name='経常利益'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='result',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='retained_earnings',
            field=models.FloatField(blank=True, null=True, verbose_name='利益剰余金'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='retained_earnings_dividends',
            field=models.FloatField(blank=True, null=True, verbose_name='剰余金の配当'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='revenue',
            field=models.FloatField(blank=True, default=465406000000, null=True, verbose_name='売上高'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='share_buyback',
            field=models.FloatField(blank=True, null=True, verbose_name='自社株買い'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='short_term_loans',
            field=models.FloatField(blank=True, null=True, verbose_name='短期借入金'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='total_assets',
            field=models.FloatField(blank=True, null=True, verbose_name='総資産'),
        ),
    ]
